name = "PassStores"
uuid = "4383d8c7-e827-43b8-a3d6-a47e3cac7fdc"
version = "0.1.0"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Logging = "1.10.0"
julia = "1.10"
